[2023-04-25T23:38:26.355+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: treino-02.calcula-idade-media scheduled__2023-04-23T22:46:00+00:00 [queued]>
[2023-04-25T23:38:26.493+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: treino-02.calcula-idade-media scheduled__2023-04-23T22:46:00+00:00 [queued]>
[2023-04-25T23:38:26.530+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-25T23:38:26.542+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 2
[2023-04-25T23:38:26.551+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-25T23:38:27.123+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): calcula-idade-media> on 2023-04-23 22:46:00+00:00
[2023-04-25T23:38:27.230+0000] {standard_task_runner.py:55} INFO - Started process 1417 to run task
[2023-04-25T23:38:27.320+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'treino-02', 'calcula-idade-media', 'scheduled__2023-04-23T22:46:00+00:00', '--job-id', '251', '--raw', '--subdir', 'DAGS_FOLDER/treino02.py', '--cfg-path', '/tmp/tmpzd_yacv3']
[2023-04-25T23:38:27.343+0000] {standard_task_runner.py:83} INFO - Job 251: Subtask calcula-idade-media
[2023-04-25T23:38:28.624+0000] {task_command.py:389} INFO - Running <TaskInstance: treino-02.calcula-idade-media scheduled__2023-04-23T22:46:00+00:00 [running]> on host b7947b05bca0
[2023-04-25T23:38:29.503+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=test@example.com,test2@example.com
AIRFLOW_CTX_DAG_OWNER=augsmachado
AIRFLOW_CTX_DAG_ID=treino-02
AIRFLOW_CTX_TASK_ID=calcula-idade-media
AIRFLOW_CTX_EXECUTION_DATE=2023-04-23T22:46:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-23T22:46:00+00:00
[2023-04-25T23:38:29.579+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/treino02.py", line 40, in calculate_mean_age
    '~/Users/augsmachado/Desktop/Development/airflow-docker/files/train.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/Users/augsmachado/Desktop/Development/airflow-docker/files/train.csv'
[2023-04-25T23:38:29.659+0000] {taskinstance.py:1332} INFO - Marking task as UP_FOR_RETRY. dag_id=treino-02, task_id=calcula-idade-media, execution_date=20230423T224600, start_date=20230425T233826, end_date=20230425T233829
[2023-04-25T23:38:29.809+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 251 for task calcula-idade-media ([Errno 2] No such file or directory: '/home/airflow/Users/augsmachado/Desktop/Development/airflow-docker/files/train.csv'; 1417)
[2023-04-25T23:38:30.037+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-25T23:38:30.266+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
