[2023-04-25T23:37:28.085+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: treino-02.get-data scheduled__2023-04-23T22:28:00+00:00 [queued]>
[2023-04-25T23:37:28.195+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: treino-02.get-data scheduled__2023-04-23T22:28:00+00:00 [queued]>
[2023-04-25T23:37:28.198+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-25T23:37:28.202+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 2
[2023-04-25T23:37:28.207+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-25T23:37:28.497+0000] {taskinstance.py:1309} INFO - Executing <Task(BashOperator): get-data> on 2023-04-23 22:28:00+00:00
[2023-04-25T23:37:28.626+0000] {standard_task_runner.py:55} INFO - Started process 1325 to run task
[2023-04-25T23:37:28.745+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'treino-02', 'get-data', 'scheduled__2023-04-23T22:28:00+00:00', '--job-id', '232', '--raw', '--subdir', 'DAGS_FOLDER/treino02.py', '--cfg-path', '/tmp/tmp86ksimeu']
[2023-04-25T23:37:28.756+0000] {standard_task_runner.py:83} INFO - Job 232: Subtask get-data
[2023-04-25T23:37:29.831+0000] {task_command.py:389} INFO - Running <TaskInstance: treino-02.get-data scheduled__2023-04-23T22:28:00+00:00 [running]> on host b7947b05bca0
[2023-04-25T23:37:30.543+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=test@example.com,test2@example.com
AIRFLOW_CTX_DAG_OWNER=augsmachado
AIRFLOW_CTX_DAG_ID=treino-02
AIRFLOW_CTX_TASK_ID=get-data
AIRFLOW_CTX_EXECUTION_DATE=2023-04-23T22:28:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-23T22:28:00+00:00
[2023-04-25T23:37:30.598+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-04-25T23:37:30.612+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'curl -o ~/Users/augsmachado/Desktop/Development/***-docker/files/titanic.csv https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv']
[2023-04-25T23:37:30.816+0000] {subprocess.py:86} INFO - Output:
[2023-04-25T23:37:31.179+0000] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2023-04-25T23:37:31.184+0000] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2023-04-25T23:37:31.438+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to create the file
[2023-04-25T23:37:31.454+0000] {subprocess.py:93} INFO - Warning: /home/***/Users/augsmachado/Desktop/Development/***-docker/fil
[2023-04-25T23:37:31.468+0000] {subprocess.py:93} INFO - Warning: es/titanic.csv: No such file or directory
[2023-04-25T23:37:31.470+0000] {subprocess.py:93} INFO -   2 60302    2  1413    0     0   5252      0  0:00:11 --:--:--  0:00:11  5272
[2023-04-25T23:37:31.496+0000] {subprocess.py:93} INFO - curl: (23) Failure writing output to destination
[2023-04-25T23:37:31.519+0000] {subprocess.py:97} INFO - Command exited with return code 23
[2023-04-25T23:37:31.766+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 23.
[2023-04-25T23:37:31.814+0000] {taskinstance.py:1332} INFO - Marking task as UP_FOR_RETRY. dag_id=treino-02, task_id=get-data, execution_date=20230423T222800, start_date=20230425T233728, end_date=20230425T233731
[2023-04-25T23:37:31.978+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 232 for task get-data (Bash command failed. The command returned a non-zero exit code 23.; 1325)
[2023-04-25T23:37:32.164+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-25T23:37:32.436+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
