[2023-04-25T23:31:27.932+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: treino-02.get-data scheduled__2023-04-23T21:02:00+00:00 [queued]>
[2023-04-25T23:31:27.985+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: treino-02.get-data scheduled__2023-04-23T21:02:00+00:00 [queued]>
[2023-04-25T23:31:28.007+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-25T23:31:28.009+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 2
[2023-04-25T23:31:28.011+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-25T23:31:28.102+0000] {taskinstance.py:1309} INFO - Executing <Task(BashOperator): get-data> on 2023-04-23 21:02:00+00:00
[2023-04-25T23:31:28.132+0000] {standard_task_runner.py:55} INFO - Started process 764 to run task
[2023-04-25T23:31:28.223+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'treino-02', 'get-data', 'scheduled__2023-04-23T21:02:00+00:00', '--job-id', '145', '--raw', '--subdir', 'DAGS_FOLDER/treino02.py', '--cfg-path', '/tmp/tmpb85yboy9']
[2023-04-25T23:31:28.236+0000] {standard_task_runner.py:83} INFO - Job 145: Subtask get-data
[2023-04-25T23:31:28.763+0000] {task_command.py:389} INFO - Running <TaskInstance: treino-02.get-data scheduled__2023-04-23T21:02:00+00:00 [running]> on host b7947b05bca0
[2023-04-25T23:31:29.221+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=test@example.com,test2@example.com
AIRFLOW_CTX_DAG_OWNER=augsmachado
AIRFLOW_CTX_DAG_ID=treino-02
AIRFLOW_CTX_TASK_ID=get-data
AIRFLOW_CTX_EXECUTION_DATE=2023-04-23T21:02:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-23T21:02:00+00:00
[2023-04-25T23:31:29.245+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-04-25T23:31:29.248+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'curl -o ~/Users/augsmachado/Desktop/Development/***-docker/files/titanic.csv https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv']
[2023-04-25T23:31:29.304+0000] {subprocess.py:86} INFO - Output:
[2023-04-25T23:31:29.334+0000] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2023-04-25T23:31:29.336+0000] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2023-04-25T23:31:29.453+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to create the file
[2023-04-25T23:31:29.459+0000] {subprocess.py:93} INFO - Warning: /home/***/Users/augsmachado/Desktop/Development/***-docker/fil
[2023-04-25T23:31:29.460+0000] {subprocess.py:93} INFO - Warning: es/titanic.csv: No such file or directory
[2023-04-25T23:31:29.461+0000] {subprocess.py:93} INFO -   2 60302    2  1369    0     0  11408      0  0:00:05 --:--:--  0:00:05 11504
[2023-04-25T23:31:29.463+0000] {subprocess.py:93} INFO - curl: (23) Failure writing output to destination
[2023-04-25T23:31:29.465+0000] {subprocess.py:97} INFO - Command exited with return code 23
[2023-04-25T23:31:29.498+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 23.
[2023-04-25T23:31:29.522+0000] {taskinstance.py:1332} INFO - Marking task as UP_FOR_RETRY. dag_id=treino-02, task_id=get-data, execution_date=20230423T210200, start_date=20230425T233127, end_date=20230425T233129
[2023-04-25T23:31:29.573+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 145 for task get-data (Bash command failed. The command returned a non-zero exit code 23.; 764)
[2023-04-25T23:31:29.705+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-25T23:31:29.986+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
