[2023-04-25T23:31:17.247+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: treino-02.get-data scheduled__2023-04-23T20:48:00+00:00 [queued]>
[2023-04-25T23:31:17.268+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: treino-02.get-data scheduled__2023-04-23T20:48:00+00:00 [queued]>
[2023-04-25T23:31:17.269+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-25T23:31:17.270+0000] {taskinstance.py:1289} INFO - Starting attempt 2 of 2
[2023-04-25T23:31:17.271+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-25T23:31:17.299+0000] {taskinstance.py:1309} INFO - Executing <Task(BashOperator): get-data> on 2023-04-23 20:48:00+00:00
[2023-04-25T23:31:17.317+0000] {standard_task_runner.py:55} INFO - Started process 731 to run task
[2023-04-25T23:31:17.335+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'treino-02', 'get-data', 'scheduled__2023-04-23T20:48:00+00:00', '--job-id', '139', '--raw', '--subdir', 'DAGS_FOLDER/treino02.py', '--cfg-path', '/tmp/tmpbdj_7a4n']
[2023-04-25T23:31:17.337+0000] {standard_task_runner.py:83} INFO - Job 139: Subtask get-data
[2023-04-25T23:31:17.542+0000] {task_command.py:389} INFO - Running <TaskInstance: treino-02.get-data scheduled__2023-04-23T20:48:00+00:00 [running]> on host b7947b05bca0
[2023-04-25T23:31:17.706+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=test@example.com,test2@example.com
AIRFLOW_CTX_DAG_OWNER=augsmachado
AIRFLOW_CTX_DAG_ID=treino-02
AIRFLOW_CTX_TASK_ID=get-data
AIRFLOW_CTX_EXECUTION_DATE=2023-04-23T20:48:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-23T20:48:00+00:00
[2023-04-25T23:31:17.712+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-04-25T23:31:17.714+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'curl -o ~/Users/augsmachado/Desktop/Development/***-docker/files/titanic.csv https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv']
[2023-04-25T23:31:17.747+0000] {subprocess.py:86} INFO - Output:
[2023-04-25T23:31:17.773+0000] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2023-04-25T23:31:17.775+0000] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2023-04-25T23:31:17.931+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to create the file
[2023-04-25T23:31:17.933+0000] {subprocess.py:93} INFO - Warning: /home/***/Users/augsmachado/Desktop/Development/***-docker/fil
[2023-04-25T23:31:17.934+0000] {subprocess.py:93} INFO - Warning: es/titanic.csv: No such file or directory
[2023-04-25T23:31:17.935+0000] {subprocess.py:93} INFO -   1 60302    1   858    0     0   5430      0  0:00:11 --:--:--  0:00:11  5430
[2023-04-25T23:31:17.936+0000] {subprocess.py:93} INFO - curl: (23) Failure writing output to destination
[2023-04-25T23:31:17.936+0000] {subprocess.py:97} INFO - Command exited with return code 23
[2023-04-25T23:31:17.962+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 23.
[2023-04-25T23:31:17.969+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=treino-02, task_id=get-data, execution_date=20230423T204800, start_date=20230425T233117, end_date=20230425T233117
[2023-04-25T23:31:17.987+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 139 for task get-data (Bash command failed. The command returned a non-zero exit code 23.; 731)
[2023-04-25T23:31:18.027+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-25T23:31:18.075+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
