[2023-04-25T23:25:26.208+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: treino-02.get-data scheduled__2023-04-23T19:42:00+00:00 [queued]>
[2023-04-25T23:25:26.292+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: treino-02.get-data scheduled__2023-04-23T19:42:00+00:00 [queued]>
[2023-04-25T23:25:26.294+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-25T23:25:26.297+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 2
[2023-04-25T23:25:26.305+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-25T23:25:26.684+0000] {taskinstance.py:1309} INFO - Executing <Task(BashOperator): get-data> on 2023-04-23 19:42:00+00:00
[2023-04-25T23:25:26.725+0000] {standard_task_runner.py:55} INFO - Started process 173 to run task
[2023-04-25T23:25:26.809+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'treino-02', 'get-data', 'scheduled__2023-04-23T19:42:00+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/treino02.py', '--cfg-path', '/tmp/tmpj17ovj_g']
[2023-04-25T23:25:26.818+0000] {standard_task_runner.py:83} INFO - Job 45: Subtask get-data
[2023-04-25T23:25:28.870+0000] {task_command.py:389} INFO - Running <TaskInstance: treino-02.get-data scheduled__2023-04-23T19:42:00+00:00 [running]> on host b7947b05bca0
[2023-04-25T23:25:30.996+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=test@example.com,test2@example.com
AIRFLOW_CTX_DAG_OWNER=augsmachado
AIRFLOW_CTX_DAG_ID=treino-02
AIRFLOW_CTX_TASK_ID=get-data
AIRFLOW_CTX_EXECUTION_DATE=2023-04-23T19:42:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-23T19:42:00+00:00
[2023-04-25T23:25:31.135+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-04-25T23:25:31.163+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'curl https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv -o ~/Users/augsmachado/Desktop/Development/***-docker/files/train.csv']
[2023-04-25T23:25:31.440+0000] {subprocess.py:86} INFO - Output:
[2023-04-25T23:25:32.174+0000] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2023-04-25T23:25:32.193+0000] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2023-04-25T23:25:32.672+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to create the file
[2023-04-25T23:25:32.674+0000] {subprocess.py:93} INFO - Warning: /home/***/Users/augsmachado/Desktop/Development/***-docker/fil
[2023-04-25T23:25:32.676+0000] {subprocess.py:93} INFO - Warning: es/train.csv: No such file or directory
[2023-04-25T23:25:32.677+0000] {subprocess.py:93} INFO -   1 60302    1   901    0     0   1794      0  0:00:33 --:--:--  0:00:33  1794
[2023-04-25T23:25:32.677+0000] {subprocess.py:93} INFO - curl: (23) Failure writing output to destination
[2023-04-25T23:25:32.776+0000] {subprocess.py:97} INFO - Command exited with return code 23
[2023-04-25T23:25:33.297+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 23.
[2023-04-25T23:25:33.484+0000] {taskinstance.py:1332} INFO - Marking task as UP_FOR_RETRY. dag_id=treino-02, task_id=get-data, execution_date=20230423T194200, start_date=20230425T232526, end_date=20230425T232533
[2023-04-25T23:25:34.047+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 45 for task get-data (Bash command failed. The command returned a non-zero exit code 23.; 173)
[2023-04-25T23:25:34.312+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-25T23:25:35.910+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
