[2023-04-25T23:35:38.227+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: treino-02.get-data scheduled__2023-04-23T21:42:00+00:00 [queued]>
[2023-04-25T23:35:38.240+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: treino-02.get-data scheduled__2023-04-23T21:42:00+00:00 [queued]>
[2023-04-25T23:35:38.241+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-25T23:35:38.241+0000] {taskinstance.py:1289} INFO - Starting attempt 2 of 2
[2023-04-25T23:35:38.242+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-25T23:35:38.256+0000] {taskinstance.py:1309} INFO - Executing <Task(BashOperator): get-data> on 2023-04-23 21:42:00+00:00
[2023-04-25T23:35:38.264+0000] {standard_task_runner.py:55} INFO - Started process 1136 to run task
[2023-04-25T23:35:38.269+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'treino-02', 'get-data', 'scheduled__2023-04-23T21:42:00+00:00', '--job-id', '204', '--raw', '--subdir', 'DAGS_FOLDER/treino02.py', '--cfg-path', '/tmp/tmp47mmfg_b']
[2023-04-25T23:35:38.271+0000] {standard_task_runner.py:83} INFO - Job 204: Subtask get-data
[2023-04-25T23:35:38.368+0000] {task_command.py:389} INFO - Running <TaskInstance: treino-02.get-data scheduled__2023-04-23T21:42:00+00:00 [running]> on host b7947b05bca0
[2023-04-25T23:35:38.439+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=test@example.com,test2@example.com
AIRFLOW_CTX_DAG_OWNER=augsmachado
AIRFLOW_CTX_DAG_ID=treino-02
AIRFLOW_CTX_TASK_ID=get-data
AIRFLOW_CTX_EXECUTION_DATE=2023-04-23T21:42:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-23T21:42:00+00:00
[2023-04-25T23:35:38.442+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-04-25T23:35:38.444+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'curl -o ~/Users/augsmachado/Desktop/Development/***-docker/files/titanic.csv https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv']
[2023-04-25T23:35:38.458+0000] {subprocess.py:86} INFO - Output:
[2023-04-25T23:35:38.485+0000] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2023-04-25T23:35:38.486+0000] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2023-04-25T23:35:38.607+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to create the file
[2023-04-25T23:35:38.608+0000] {subprocess.py:93} INFO - Warning: /home/***/Users/augsmachado/Desktop/Development/***-docker/fil
[2023-04-25T23:35:38.609+0000] {subprocess.py:93} INFO - Warning: es/titanic.csv: No such file or directory
[2023-04-25T23:35:38.610+0000] {subprocess.py:93} INFO -   2 60302    2  1369    0     0  11130      0  0:00:05 --:--:--  0:00:05 11221
[2023-04-25T23:35:38.610+0000] {subprocess.py:93} INFO - curl: (23) Failure writing output to destination
[2023-04-25T23:35:38.612+0000] {subprocess.py:97} INFO - Command exited with return code 23
[2023-04-25T23:35:38.634+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 23.
[2023-04-25T23:35:38.639+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=treino-02, task_id=get-data, execution_date=20230423T214200, start_date=20230425T233538, end_date=20230425T233538
[2023-04-25T23:35:38.651+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 204 for task get-data (Bash command failed. The command returned a non-zero exit code 23.; 1136)
[2023-04-25T23:35:38.686+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-25T23:35:38.714+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
