[2023-04-25T23:41:47.731+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: treino-02.mostra-idade scheduled__2023-04-23T22:30:00+00:00 [queued]>
[2023-04-25T23:41:48.399+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: treino-02.mostra-idade scheduled__2023-04-23T22:30:00+00:00 [queued]>
[2023-04-25T23:41:48.420+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-25T23:41:48.424+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 2
[2023-04-25T23:41:48.427+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-25T23:41:48.504+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): mostra-idade> on 2023-04-23 22:30:00+00:00
[2023-04-25T23:41:48.693+0000] {standard_task_runner.py:55} INFO - Started process 1556 to run task
[2023-04-25T23:41:48.804+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'treino-02', 'mostra-idade', 'scheduled__2023-04-23T22:30:00+00:00', '--job-id', '273', '--raw', '--subdir', 'DAGS_FOLDER/treino02.py', '--cfg-path', '/tmp/tmpt4srvbf5']
[2023-04-25T23:41:48.820+0000] {standard_task_runner.py:83} INFO - Job 273: Subtask mostra-idade
[2023-04-25T23:41:50.570+0000] {task_command.py:389} INFO - Running <TaskInstance: treino-02.mostra-idade scheduled__2023-04-23T22:30:00+00:00 [running]> on host b7947b05bca0
[2023-04-25T23:41:51.776+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=test@example.com,test2@example.com
AIRFLOW_CTX_DAG_OWNER=augsmachado
AIRFLOW_CTX_DAG_ID=treino-02
AIRFLOW_CTX_TASK_ID=mostra-idade
AIRFLOW_CTX_EXECUTION_DATE=2023-04-23T22:30:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-23T22:30:00+00:00
[2023-04-25T23:41:51.799+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/treino02.py", line 45, in print_age
    value = context['task_instance'].xcom_pull(tas_ids='calcula-idade-media')
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
TypeError: xcom_pull() got an unexpected keyword argument 'tas_ids'
[2023-04-25T23:41:51.839+0000] {taskinstance.py:1332} INFO - Marking task as UP_FOR_RETRY. dag_id=treino-02, task_id=mostra-idade, execution_date=20230423T223000, start_date=20230425T234147, end_date=20230425T234151
[2023-04-25T23:41:51.891+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 273 for task mostra-idade (xcom_pull() got an unexpected keyword argument 'tas_ids'; 1556)
[2023-04-25T23:41:52.337+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-25T23:41:52.575+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
