[2023-04-25T23:25:17.282+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: treino-02.get-data scheduled__2023-04-23T19:36:00+00:00 [queued]>
[2023-04-25T23:25:17.318+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: treino-02.get-data scheduled__2023-04-23T19:36:00+00:00 [queued]>
[2023-04-25T23:25:17.319+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-25T23:25:17.321+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 2
[2023-04-25T23:25:17.322+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-25T23:25:17.381+0000] {taskinstance.py:1309} INFO - Executing <Task(BashOperator): get-data> on 2023-04-23 19:36:00+00:00
[2023-04-25T23:25:17.420+0000] {standard_task_runner.py:55} INFO - Started process 154 to run task
[2023-04-25T23:25:17.481+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'treino-02', 'get-data', 'scheduled__2023-04-23T19:36:00+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/treino02.py', '--cfg-path', '/tmp/tmp7lriwco2']
[2023-04-25T23:25:17.487+0000] {standard_task_runner.py:83} INFO - Job 42: Subtask get-data
[2023-04-25T23:25:18.229+0000] {task_command.py:389} INFO - Running <TaskInstance: treino-02.get-data scheduled__2023-04-23T19:36:00+00:00 [running]> on host b7947b05bca0
[2023-04-25T23:25:18.807+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=test@example.com,test2@example.com
AIRFLOW_CTX_DAG_OWNER=augsmachado
AIRFLOW_CTX_DAG_ID=treino-02
AIRFLOW_CTX_TASK_ID=get-data
AIRFLOW_CTX_EXECUTION_DATE=2023-04-23T19:36:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-23T19:36:00+00:00
[2023-04-25T23:25:18.862+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-04-25T23:25:18.885+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'curl https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv -o ~/Users/augsmachado/Desktop/Development/***-docker/files/train.csv']
[2023-04-25T23:25:19.174+0000] {subprocess.py:86} INFO - Output:
[2023-04-25T23:25:19.382+0000] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2023-04-25T23:25:19.388+0000] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2023-04-25T23:25:19.597+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to create the file
[2023-04-25T23:25:19.600+0000] {subprocess.py:93} INFO - Warning: /home/***/Users/augsmachado/Desktop/Development/***-docker/fil
[2023-04-25T23:25:19.602+0000] {subprocess.py:93} INFO - Warning: es/train.csv: No such file or directory
[2023-04-25T23:25:19.606+0000] {subprocess.py:93} INFO -   1 60302    1   857    0     0   4100      0  0:00:14 --:--:--  0:00:14  4100
[2023-04-25T23:25:19.613+0000] {subprocess.py:93} INFO - curl: (23) Failure writing output to destination
[2023-04-25T23:25:19.654+0000] {subprocess.py:97} INFO - Command exited with return code 23
[2023-04-25T23:25:20.299+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 23.
[2023-04-25T23:25:20.688+0000] {taskinstance.py:1332} INFO - Marking task as UP_FOR_RETRY. dag_id=treino-02, task_id=get-data, execution_date=20230423T193600, start_date=20230425T232517, end_date=20230425T232520
[2023-04-25T23:25:21.124+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 42 for task get-data (Bash command failed. The command returned a non-zero exit code 23.; 154)
[2023-04-25T23:25:21.945+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-25T23:25:23.614+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
