[2023-04-25T23:27:57.067+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: treino-02.get-data scheduled__2023-04-23T20:20:00+00:00 [queued]>
[2023-04-25T23:27:57.320+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: treino-02.get-data scheduled__2023-04-23T20:20:00+00:00 [queued]>
[2023-04-25T23:27:57.333+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-25T23:27:57.341+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 2
[2023-04-25T23:27:57.348+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-25T23:27:57.580+0000] {taskinstance.py:1309} INFO - Executing <Task(BashOperator): get-data> on 2023-04-23 20:20:00+00:00
[2023-04-25T23:27:57.664+0000] {standard_task_runner.py:55} INFO - Started process 436 to run task
[2023-04-25T23:27:57.772+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'treino-02', 'get-data', 'scheduled__2023-04-23T20:20:00+00:00', '--job-id', '90', '--raw', '--subdir', 'DAGS_FOLDER/treino02.py', '--cfg-path', '/tmp/tmp5l4gpnw3']
[2023-04-25T23:27:57.792+0000] {standard_task_runner.py:83} INFO - Job 90: Subtask get-data
[2023-04-25T23:27:58.672+0000] {task_command.py:389} INFO - Running <TaskInstance: treino-02.get-data scheduled__2023-04-23T20:20:00+00:00 [running]> on host b7947b05bca0
[2023-04-25T23:27:59.666+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=test@example.com,test2@example.com
AIRFLOW_CTX_DAG_OWNER=augsmachado
AIRFLOW_CTX_DAG_ID=treino-02
AIRFLOW_CTX_TASK_ID=get-data
AIRFLOW_CTX_EXECUTION_DATE=2023-04-23T20:20:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-23T20:20:00+00:00
[2023-04-25T23:27:59.682+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-04-25T23:27:59.687+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'curl https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv -o ~/Users/augsmachado/Desktop/Development/***-docker/files/titanic.csv']
[2023-04-25T23:27:59.773+0000] {subprocess.py:86} INFO - Output:
[2023-04-25T23:27:59.972+0000] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2023-04-25T23:27:59.976+0000] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2023-04-25T23:28:00.324+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to create the file
[2023-04-25T23:28:00.347+0000] {subprocess.py:93} INFO - Warning: /home/***/Users/augsmachado/Desktop/Development/***-docker/fil
[2023-04-25T23:28:00.350+0000] {subprocess.py:93} INFO - Warning: es/titanic.csv: No such file or directory
[2023-04-25T23:28:00.351+0000] {subprocess.py:93} INFO -   1 60302    1   902    0     0   2622      0  0:00:22 --:--:--  0:00:22  2622
[2023-04-25T23:28:00.353+0000] {subprocess.py:93} INFO - curl: (23) Failure writing output to destination
[2023-04-25T23:28:00.367+0000] {subprocess.py:97} INFO - Command exited with return code 23
[2023-04-25T23:28:00.851+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 23.
[2023-04-25T23:28:00.941+0000] {taskinstance.py:1332} INFO - Marking task as UP_FOR_RETRY. dag_id=treino-02, task_id=get-data, execution_date=20230423T202000, start_date=20230425T232757, end_date=20230425T232800
[2023-04-25T23:28:01.364+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 90 for task get-data (Bash command failed. The command returned a non-zero exit code 23.; 436)
[2023-04-25T23:28:02.328+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-25T23:28:02.984+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
