[2023-04-25T23:31:47.282+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: treino-02.get-data scheduled__2023-04-23T21:22:00+00:00 [queued]>
[2023-04-25T23:31:47.348+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: treino-02.get-data scheduled__2023-04-23T21:22:00+00:00 [queued]>
[2023-04-25T23:31:47.353+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-25T23:31:47.355+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 2
[2023-04-25T23:31:47.356+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-25T23:31:47.484+0000] {taskinstance.py:1309} INFO - Executing <Task(BashOperator): get-data> on 2023-04-23 21:22:00+00:00
[2023-04-25T23:31:47.598+0000] {standard_task_runner.py:55} INFO - Started process 815 to run task
[2023-04-25T23:31:47.624+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'treino-02', 'get-data', 'scheduled__2023-04-23T21:22:00+00:00', '--job-id', '156', '--raw', '--subdir', 'DAGS_FOLDER/treino02.py', '--cfg-path', '/tmp/tmpn2_xgqtd']
[2023-04-25T23:31:47.629+0000] {standard_task_runner.py:83} INFO - Job 156: Subtask get-data
[2023-04-25T23:31:48.036+0000] {task_command.py:389} INFO - Running <TaskInstance: treino-02.get-data scheduled__2023-04-23T21:22:00+00:00 [running]> on host b7947b05bca0
[2023-04-25T23:31:48.325+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=test@example.com,test2@example.com
AIRFLOW_CTX_DAG_OWNER=augsmachado
AIRFLOW_CTX_DAG_ID=treino-02
AIRFLOW_CTX_TASK_ID=get-data
AIRFLOW_CTX_EXECUTION_DATE=2023-04-23T21:22:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-23T21:22:00+00:00
[2023-04-25T23:31:48.348+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-04-25T23:31:48.357+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'curl -o ~/Users/augsmachado/Desktop/Development/***-docker/files/titanic.csv https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv']
[2023-04-25T23:31:48.405+0000] {subprocess.py:86} INFO - Output:
[2023-04-25T23:31:48.429+0000] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2023-04-25T23:31:48.430+0000] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2023-04-25T23:31:48.543+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to create the file
[2023-04-25T23:31:48.544+0000] {subprocess.py:93} INFO - Warning: /home/***/Users/augsmachado/Desktop/Development/***-docker/fil
[2023-04-25T23:31:48.545+0000] {subprocess.py:93} INFO - Warning: es/titanic.csv: No such file or directory
[2023-04-25T23:31:48.545+0000] {subprocess.py:93} INFO -   2 60302    2  1369    0     0  11130      0  0:00:05 --:--:--  0:00:05 11130
[2023-04-25T23:31:48.549+0000] {subprocess.py:93} INFO - curl: (23) Failure writing output to destination
[2023-04-25T23:31:48.551+0000] {subprocess.py:97} INFO - Command exited with return code 23
[2023-04-25T23:31:48.592+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 23.
[2023-04-25T23:31:48.600+0000] {taskinstance.py:1332} INFO - Marking task as UP_FOR_RETRY. dag_id=treino-02, task_id=get-data, execution_date=20230423T212200, start_date=20230425T233147, end_date=20230425T233148
[2023-04-25T23:31:48.629+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 156 for task get-data (Bash command failed. The command returned a non-zero exit code 23.; 815)
[2023-04-25T23:31:48.722+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-25T23:31:49.084+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
