[2023-04-25T23:15:02.060+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: treino-02.get-data scheduled__2023-04-23T19:12:00+00:00 [queued]>
[2023-04-25T23:15:02.160+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: treino-02.get-data scheduled__2023-04-23T19:12:00+00:00 [queued]>
[2023-04-25T23:15:02.163+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-25T23:15:02.165+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 2
[2023-04-25T23:15:02.167+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-25T23:15:02.349+0000] {taskinstance.py:1309} INFO - Executing <Task(BashOperator): get-data> on 2023-04-23 19:12:00+00:00
[2023-04-25T23:15:02.463+0000] {standard_task_runner.py:55} INFO - Started process 860 to run task
[2023-04-25T23:15:02.665+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'treino-02', 'get-data', 'scheduled__2023-04-23T19:12:00+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/treino02.py', '--cfg-path', '/tmp/tmpb0qeqdrq']
[2023-04-25T23:15:02.670+0000] {standard_task_runner.py:83} INFO - Job 23: Subtask get-data
[2023-04-25T23:15:03.306+0000] {task_command.py:389} INFO - Running <TaskInstance: treino-02.get-data scheduled__2023-04-23T19:12:00+00:00 [running]> on host b7947b05bca0
[2023-04-25T23:15:04.119+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=test@example.com,test2@example.com
AIRFLOW_CTX_DAG_OWNER=augsmachado
AIRFLOW_CTX_DAG_ID=treino-02
AIRFLOW_CTX_TASK_ID=get-data
AIRFLOW_CTX_EXECUTION_DATE=2023-04-23T19:12:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-23T19:12:00+00:00
[2023-04-25T23:15:04.193+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-04-25T23:15:04.231+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'curl https://raw.githubusercontent.com/A3Data/hermione/master/hermione/file_text/train.csv -o ~/Users/augsmachado/Desktop/Development/***-docker/files/train.csv']
[2023-04-25T23:15:04.385+0000] {subprocess.py:86} INFO - Output:
[2023-04-25T23:15:04.435+0000] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2023-04-25T23:15:04.437+0000] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2023-04-25T23:15:04.608+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to create the file
[2023-04-25T23:15:04.610+0000] {subprocess.py:93} INFO - Warning: /home/***/Users/augsmachado/Desktop/Development/***-docker/fil
[2023-04-25T23:15:04.611+0000] {subprocess.py:93} INFO - Warning: es/train.csv: No such file or directory
[2023-04-25T23:15:04.611+0000] {subprocess.py:93} INFO - 100    14  100    14    0     0     80      0 --:--:-- --:--:-- --:--:--    80
[2023-04-25T23:15:04.612+0000] {subprocess.py:93} INFO - curl: (23) Failure writing output to destination
[2023-04-25T23:15:04.618+0000] {subprocess.py:97} INFO - Command exited with return code 23
[2023-04-25T23:15:04.779+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 23.
[2023-04-25T23:15:04.870+0000] {taskinstance.py:1332} INFO - Marking task as UP_FOR_RETRY. dag_id=treino-02, task_id=get-data, execution_date=20230423T191200, start_date=20230425T231502, end_date=20230425T231504
[2023-04-25T23:15:05.049+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 23 for task get-data (Bash command failed. The command returned a non-zero exit code 23.; 860)
[2023-04-25T23:15:05.176+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-25T23:15:05.567+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
