[2023-04-25T23:35:35.265+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: treino-02.get-data scheduled__2023-04-23T21:50:00+00:00 [queued]>
[2023-04-25T23:35:35.274+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: treino-02.get-data scheduled__2023-04-23T21:50:00+00:00 [queued]>
[2023-04-25T23:35:35.275+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-25T23:35:35.275+0000] {taskinstance.py:1289} INFO - Starting attempt 2 of 2
[2023-04-25T23:35:35.276+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-25T23:35:35.294+0000] {taskinstance.py:1309} INFO - Executing <Task(BashOperator): get-data> on 2023-04-23 21:50:00+00:00
[2023-04-25T23:35:35.305+0000] {standard_task_runner.py:55} INFO - Started process 1129 to run task
[2023-04-25T23:35:35.311+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'treino-02', 'get-data', 'scheduled__2023-04-23T21:50:00+00:00', '--job-id', '203', '--raw', '--subdir', 'DAGS_FOLDER/treino02.py', '--cfg-path', '/tmp/tmpnrtu8h00']
[2023-04-25T23:35:35.313+0000] {standard_task_runner.py:83} INFO - Job 203: Subtask get-data
[2023-04-25T23:35:35.415+0000] {task_command.py:389} INFO - Running <TaskInstance: treino-02.get-data scheduled__2023-04-23T21:50:00+00:00 [running]> on host b7947b05bca0
[2023-04-25T23:35:35.500+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=test@example.com,test2@example.com
AIRFLOW_CTX_DAG_OWNER=augsmachado
AIRFLOW_CTX_DAG_ID=treino-02
AIRFLOW_CTX_TASK_ID=get-data
AIRFLOW_CTX_EXECUTION_DATE=2023-04-23T21:50:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-23T21:50:00+00:00
[2023-04-25T23:35:35.504+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-04-25T23:35:35.505+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'curl -o ~/Users/augsmachado/Desktop/Development/***-docker/files/titanic.csv https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv']
[2023-04-25T23:35:35.521+0000] {subprocess.py:86} INFO - Output:
[2023-04-25T23:35:35.546+0000] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2023-04-25T23:35:35.551+0000] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2023-04-25T23:35:39.488+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0Warning: Failed to create the file
[2023-04-25T23:35:39.523+0000] {subprocess.py:93} INFO - Warning: /home/***/Users/augsmachado/Desktop/Development/***-docker/fil
[2023-04-25T23:35:39.525+0000] {subprocess.py:93} INFO - Warning: es/titanic.csv: No such file or directory
[2023-04-25T23:35:39.526+0000] {subprocess.py:93} INFO -   1 60302    1   859    0     0    218      0  0:04:36  0:00:03  0:04:33   217
[2023-04-25T23:35:39.527+0000] {subprocess.py:93} INFO - curl: (23) Failure writing output to destination
[2023-04-25T23:35:39.529+0000] {subprocess.py:97} INFO - Command exited with return code 23
[2023-04-25T23:35:39.569+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 23.
[2023-04-25T23:35:39.587+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=treino-02, task_id=get-data, execution_date=20230423T215000, start_date=20230425T233535, end_date=20230425T233539
[2023-04-25T23:35:39.611+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 203 for task get-data (Bash command failed. The command returned a non-zero exit code 23.; 1129)
[2023-04-25T23:35:39.674+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-25T23:35:39.791+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
